services:
  - type: web
    name: ai-legal-assistant-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://your-vercel-app.vercel.app
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
